## Lecture 7: Pandas

In [1]:
#!pip install pandas

In [2]:
import numpy as np
import pandas as pd

In [3]:
s1 = pd.Series([12,123,123,123])
print(s1)

0     12
1    123
2    123
3    123
dtype: int64

In [4]:
s2 = pd.Series(data=[83,2,34,2], index=['a','b','c','d'])
print(s2)

a    83
b     2
c    34
d     2
dtype: int64

In [5]:
arr = np.array([[1,2,3],
                [4,5,6]])
df1 = pd.DataFrame(data=arr, 
                   index=['r1','r2'],
                   columns=['c1','c2','c3'])
print(df1)

    c1  c2  c3
r1   1   2   3
r2   4   5   6

In [6]:
df2 = pd.DataFrame({'col1':{"c1":1,"c2":2,"c3":3},
                   'col2':{"c1":1,"c2":2,"c3":3}})
df2

    col1  col2
c1     1     1
c2     2     2
c3     3     3

In [7]:
type(s1)

pandas.core.series.Series

In [8]:
type(df1)

pandas.core.frame.DataFrame

In [9]:
s1

0     12
1    123
2    123
3    123
dtype: int64

In [10]:
s1.values #data

array([ 12, 123, 123, 123])

In [11]:
s1.index #index

RangeIndex(start=0, stop=4, step=1)

In [12]:
s2.index

Index(['a', 'b', 'c', 'd'], dtype='object')

In [13]:
df1.values

array([[1, 2, 3],
       [4, 5, 6]])

In [14]:
df2.values

array([[1, 1],
       [2, 2],
       [3, 3]])

In [15]:
df1

    c1  c2  c3
r1   1   2   3
r2   4   5   6

In [16]:
df1.index

Index(['r1', 'r2'], dtype='object')

In [17]:
df1.columns

Index(['c1', 'c2', 'c3'], dtype='object')

In [18]:
s2

a    83
b     2
c    34
d     2
dtype: int64

In [19]:
s2['c']

np.int64(34)

In [20]:
s2['c'] = 'new'
s2

C:\Users\Admin\AppData\Local\Temp\ipykernel_12208\2078390357.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'new' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  s2['c'] = 'new'

a     83
b      2
c    new
d      2
dtype: object

In [21]:
s1

0     12
1    123
2    123
3    123
dtype: int64

In [22]:
s1[:2]

0     12
1    123
dtype: int64

In [23]:
s2

a     83
b      2
c    new
d      2
dtype: object

In [24]:
s2[:2]

a    83
b     2
dtype: object

In [25]:
s2['a':'b']

a    83
b     2
dtype: object

In [26]:
df1

    c1  c2  c3
r1   1   2   3
r2   4   5   6

In [27]:
df1['c1']

r1    1
r2    4
Name: c1, dtype: int64

In [28]:
df1[['c1','c2']]

    c1  c2
r1   1   2
r2   4   5

In [29]:
df1

    c1  c2  c3
r1   1   2   3
r2   4   5   6

In [30]:
df1.loc['r1']

c1    1
c2    2
c3    3
Name: r1, dtype: int64

In [31]:
df1.iloc[1]

c1    4
c2    5
c3    6
Name: r2, dtype: int64

In [32]:
df2

    col1  col2
c1     1     1
c2     2     2
c3     3     3

In [33]:
df2.iloc[1:]

    col1  col2
c2     2     2
c3     3     3

In [34]:
df = pd.DataFrame({
    'A': [1, 2, 3],
    'B': [4, 5, 6],
    'C': [7, 8, 9]})
df

   A  B  C
0  1  4  7
1  2  5  8
2  3  6  9

In [35]:
#add column
df['new_col'] = [1,1,1]
df

   A  B  C  new_col
0  1  4  7        1
1  2  5  8        1
2  3  6  9        1

In [36]:
df.loc['new_id'] = [4,4,4,4]
df

        A  B  C  new_col
0       1  4  7        1
1       2  5  8        1
2       3  6  9        1
new_id  4  4  4        4

In [37]:
df.drop(columns=['new_col'], inplace=True)

In [38]:
df

        A  B  C
0       1  4  7
1       2  5  8
2       3  6  9
new_id  4  4  4

In [39]:
df.drop(index='new_id', inplace= True)

In [40]:
df

   A  B  C
0  1  4  7
1  2  5  8
2  3  6  9

In [41]:
#filter: df[filter_condition]
df[df['A']%2==1]

   A  B  C
0  1  4  7
2  3  6  9

In [42]:
df[df['B']>=5]

   A  B  C
1  2  5  8
2  3  6  9

In [43]:
df_retail = pd.read_csv('Data\OnlineRetail.csv')
type(df_retail)

pandas.core.frame.DataFrame

In [44]:
df_retail.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,539993,22386,JUMBO BAG PINK POLKADOT,10,2011-01-04 10:00:00,1.95,13313.0,United Kingdom
1,539993,21499,BLUE POLKADOT WRAP,25,2011-01-04 10:00:00,0.42,13313.0,United Kingdom
2,539993,21498,RED RETROSPOT WRAP,25,2011-01-04 10:00:00,0.42,13313.0,United Kingdom
3,539993,22379,RECYCLING BAG RETROSPOT,5,2011-01-04 10:00:00,2.10,13313.0,United Kingdom
4,539993,20718,RED RETROSPOT SHOPPER BAG,10,2011-01-04 10:00:00,1.25,13313.0,United Kingdom

In [45]:
df_retail.tail()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
203417,558637,22032,BOTANICAL LILY GREETING CARD,12,2011-06-30 20:08:00,0.42,17891.0,United Kingdom
203418,558637,22028,PENNY FARTHING BIRTHDAY CARD,12,2011-06-30 20:08:00,0.42,17891.0,United Kingdom
203419,558637,22033,BOTANICAL ROSE GREETING CARD,12,2011-06-30 20:08:00,0.42,17891.0,United Kingdom
203420,558637,22029,SPACEBOY BIRTHDAY CARD,12,2011-06-30 20:08:00,0.42,17891.0,United Kingdom
203421,558637,22024,RAINY LADIES BIRTHDAY CARD,12,2011-06-30 20:08:00,0.42,17891.0,United Kingdom

In [46]:
df_retail.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 203422 entries, 0 to 203421
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    203422 non-null  object
 1   StockCode    203422 non-null  object
 2   Description  202623 non-null  object
 3   Quantity     203422 non-null  int64
 4   InvoiceDate  203422 non-null  object
 5   UnitPrice    203422 non-null  float64
 6   CustomerID   150039 non-null  float64
 7   Country      203422 non-null  object
dtypes: float64(2), int64(1), object(5)
memory usage: 12.4+ MB

In [47]:
df

   A  B  C
0  1  4  7
1  2  5  8
2  3  6  9

In [48]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       3 non-null      int64
 1   B       3 non-null      int64
 2   C       3 non-null      int64
dtypes: int64(3)
memory usage: 204.0+ bytes

In [49]:
df_retail.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 203422 entries, 0 to 203421
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    203422 non-null  object
 1   StockCode    203422 non-null  object
 2   Description  202623 non-null  object
 3   Quantity     203422 non-null  int64
 4   InvoiceDate  203422 non-null  object
 5   UnitPrice    203422 non-null  float64
 6   CustomerID   150039 non-null  float64
 7   Country      203422 non-null  object
dtypes: float64(2), int64(1), object(5)
memory usage: 12.4+ MB

In [50]:
len(set(df_retail['StockCode']))

3531

In [51]:
df_retail['StockCode'].value_counts()

StockCode
22423     1080
85123A    1079
47566      965
85099B     924
20725      741
          ...
23039        1
23272        1
23113        1
84551        1
84679        1
Name: count, Length: 3531, dtype: int64

In [52]:
df_retail['InvoiceNo'].value_counts()

InvoiceNo
558475     705
540551     502
540848     460
541421     455
541827     429
          ...
548104       1
539996       1
558624       1
C558615      1
558529       1
Name: count, Length: 10770, dtype: int64

In [53]:
df_retail.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,539993,22386,JUMBO BAG PINK POLKADOT,10,2011-01-04 10:00:00,1.95,13313.0,United Kingdom
1,539993,21499,BLUE POLKADOT WRAP,25,2011-01-04 10:00:00,0.42,13313.0,United Kingdom
2,539993,21498,RED RETROSPOT WRAP,25,2011-01-04 10:00:00,0.42,13313.0,United Kingdom
3,539993,22379,RECYCLING BAG RETROSPOT,5,2011-01-04 10:00:00,2.10,13313.0,United Kingdom
4,539993,20718,RED RETROSPOT SHOPPER BAG,10,2011-01-04 10:00:00,1.25,13313.0,United Kingdom

In [54]:
df_retail['TotalPrice'] = df_retail['Quantity']*df_retail['UnitPrice']
df_retail.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,TotalPrice
0,539993,22386,JUMBO BAG PINK POLKADOT,10,2011-01-04 10:00:00,1.95,13313.0,United Kingdom,19.5
1,539993,21499,BLUE POLKADOT WRAP,25,2011-01-04 10:00:00,0.42,13313.0,United Kingdom,10.5
2,539993,21498,RED RETROSPOT WRAP,25,2011-01-04 10:00:00,0.42,13313.0,United Kingdom,10.5
3,539993,22379,RECYCLING BAG RETROSPOT,5,2011-01-04 10:00:00,2.10,13313.0,United Kingdom,10.5
4,539993,20718,RED RETROSPOT SHOPPER BAG,10,2011-01-04 10:00:00,1.25,13313.0,United Kingdom,12.5

In [55]:
%timeit sum(df_retail['TotalPrice'])
%timeit df_retail['TotalPrice'].sum()

83.4 ms ± 12.4 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
1.25 ms ± 219 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)

In [56]:
df_retail['TotalPrice'].sum()

np.float64(3648993.741)

In [57]:
df_retail.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 203422 entries, 0 to 203421
Data columns (total 9 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    203422 non-null  object
 1   StockCode    203422 non-null  object
 2   Description  202623 non-null  object
 3   Quantity     203422 non-null  int64
 4   InvoiceDate  203422 non-null  object
 5   UnitPrice    203422 non-null  float64
 6   CustomerID   150039 non-null  float64
 7   Country      203422 non-null  object
 8   TotalPrice   203422 non-null  float64
dtypes: float64(3), int64(1), object(5)
memory usage: 14.0+ MB

In [58]:
df_retail.isnull().sum()

InvoiceNo          0
StockCode          0
Description      799
Quantity           0
InvoiceDate        0
UnitPrice          0
CustomerID     53383
Country            0
TotalPrice         0
dtype: int64

In [59]:
df_cs = df_retail.dropna(subset=['CustomerID'])
df_cs

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,TotalPrice
0,539993,22386,JUMBO BAG PINK POLKADOT,10,2011-01-04 10:00:00,1.95,13313.0,United Kingdom,19.50
1,539993,21499,BLUE POLKADOT WRAP,25,2011-01-04 10:00:00,0.42,13313.0,United Kingdom,10.50
2,539993,21498,RED RETROSPOT WRAP,25,2011-01-04 10:00:00,0.42,13313.0,United Kingdom,10.50
3,539993,22379,RECYCLING BAG RETROSPOT,5,2011-01-04 10:00:00,2.10,13313.0,United Kingdom,10.50
4,539993,20718,RED RETROSPOT SHOPPER BAG,10,2011-01-04 10:00:00,1.25,13313.0,United Kingdom,12.50
...,...,...,...,...,...,...,...,...,...
203417,558637,22032,BOTANICAL LILY GREETING CARD,12,2011-06-30 20:08:00,0.42,17891.0,United Kingdom,5.04
203418,558637,22028,PENNY FARTHING BIRTHDAY CARD,12,2011-06-30 20:08:00,0.42,17891.0,United Kingdom,5.04
203419,558637,22033,BOTANICAL ROSE GREETING CARD,12,2011-06-30 20:08:00,0.42,17891.0,United Kingdom,5.04
203420,558637,22029,SPACEBOY BIRTHDAY CARD,12,2011-06-30 20:08:00,0.42,17891.0,United Kingdom,5.04
203421,558637,22024,RAINY LADIES BIRTHDAY CARD,12,2011-06-30 20:08:00,0.42,17891.0,United Kingdom,5.04

In [60]:
df_cs.isnull().sum()

InvoiceNo      0
StockCode      0
Description    0
Quantity       0
InvoiceDate    0
UnitPrice      0
CustomerID     0
Country        0
TotalPrice     0
dtype: int64

In [61]:
df_cs.info()

<class 'pandas.core.frame.DataFrame'>
Index: 150039 entries, 0 to 203421
Data columns (total 9 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    150039 non-null  object
 1   StockCode    150039 non-null  object
 2   Description  150039 non-null  object
 3   Quantity     150039 non-null  int64
 4   InvoiceDate  150039 non-null  object
 5   UnitPrice    150039 non-null  float64
 6   CustomerID   150039 non-null  float64
 7   Country      150039 non-null  object
 8   TotalPrice   150039 non-null  float64
dtypes: float64(3), int64(1), object(5)
memory usage: 11.4+ MB

In [80]:
df_cs['CustomerID'] = df_cs['CustomerID'].astype('int').astype('str')

In [81]:
df_cs['InvoiceDate'] = pd.to_datetime(df_cs['InvoiceDate'])

In [82]:
df_cs.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,TotalPrice
0,539993,22386,JUMBO BAG PINK POLKADOT,10,2011-01-04 10:00:00,1.95,13313,United Kingdom,19.5
1,539993,21499,BLUE POLKADOT WRAP,25,2011-01-04 10:00:00,0.42,13313,United Kingdom,10.5
2,539993,21498,RED RETROSPOT WRAP,25,2011-01-04 10:00:00,0.42,13313,United Kingdom,10.5
3,539993,22379,RECYCLING BAG RETROSPOT,5,2011-01-04 10:00:00,2.10,13313,United Kingdom,10.5
4,539993,20718,RED RETROSPOT SHOPPER BAG,10,2011-01-04 10:00:00,1.25,13313,United Kingdom,12.5

In [83]:
df_cs.drop_duplicates(inplace=True)
df_cs.info()

<class 'pandas.core.frame.DataFrame'>
Index: 145006 entries, 0 to 203421
Data columns (total 9 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    145006 non-null  object
 1   StockCode    145006 non-null  object
 2   Description  145006 non-null  object
 3   Quantity     145006 non-null  int64
 4   InvoiceDate  145006 non-null  datetime64[ns]
 5   UnitPrice    145006 non-null  float64
 6   CustomerID   145006 non-null  object
 7   Country      145006 non-null  object
 8   TotalPrice   145006 non-null  float64
dtypes: datetime64[ns](1), float64(2), int64(1), object(5)
memory usage: 15.1+ MB

In [84]:
df_cs[df_cs['InvoiceDate'].dt.quarter == 1]

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,TotalPrice
0,539993,22386,JUMBO BAG PINK POLKADOT,10,2011-01-04 10:00:00,1.95,13313,United Kingdom,19.50
1,539993,21499,BLUE POLKADOT WRAP,25,2011-01-04 10:00:00,0.42,13313,United Kingdom,10.50
2,539993,21498,RED RETROSPOT WRAP,25,2011-01-04 10:00:00,0.42,13313,United Kingdom,10.50
3,539993,22379,RECYCLING BAG RETROSPOT,5,2011-01-04 10:00:00,2.10,13313,United Kingdom,10.50
4,539993,20718,RED RETROSPOT SHOPPER BAG,10,2011-01-04 10:00:00,1.25,13313,United Kingdom,12.50
...,...,...,...,...,...,...,...,...,...
99597,548548,22423,REGENCY CAKESTAND 3 TIER,1,2011-03-31 19:54:00,12.75,17781,United Kingdom,12.75
99598,548548,21361,LOVE LARGE WOOD LETTERS,7,2011-03-31 19:54:00,12.75,17781,United Kingdom,89.25
99599,548549,84763,ZINC FINISH 15CM PLANTER POTS,100,2011-03-31 19:55:00,1.06,16365,United Kingdom,106.00
99600,548549,22222,CAKE PLATE LOVEBIRD WHITE,1,2011-03-31 19:55:00,4.95,16365,United Kingdom,4.95
99601,548549,22776,SWEETHEART CAKESTAND 3 TIER,1,2011-03-31 19:55:00,9.95,16365,United Kingdom,9.95

In [85]:
df_cs.describe()

,Quantity,InvoiceDate,UnitPrice,TotalPrice
count,145006.000000,145006,145006.000000,145006.000000
mean,13.713357,2011-04-06 09:59:48.505716992,3.319628,23.544153
min,1.000000,2011-01-04 10:00:00,0.000000,0.000000
25%,2.000000,2011-02-23 10:10:00,1.250000,5.100000
50%,6.000000,2011-04-07 11:12:00,1.950000,13.200000
75%,12.000000,2011-05-19 17:13:00,3.750000,19.800000
max,74215.000000,2011-06-30 20:08:00,8142.750000,77183.600000
std,200.301986,NaN,26.068987,239.645674

In [86]:
df_cs = df_cs[df_cs['Quantity'] > 0]

## Customer segmentation by RFM model

### RFM model
+ R: Recency. Tính bằng cách lấy ngày phân tích trừ đi ngày mua hàng
+ F: Frequency. Tính bằng số đơn (InvoiceNo)
+ M: Monetary. Tính bằng số tiền khách hàng đã chi tiêu. Tính tổng giá trị các đơn hàng mà khách hàng đã mua

In [87]:
df_cs.head(10)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,TotalPrice
0,539993,22386,JUMBO BAG PINK POLKADOT,10,2011-01-04 10:00:00,1.95,13313,United Kingdom,19.5
1,539993,21499,BLUE POLKADOT WRAP,25,2011-01-04 10:00:00,0.42,13313,United Kingdom,10.5
2,539993,21498,RED RETROSPOT WRAP,25,2011-01-04 10:00:00,0.42,13313,United Kingdom,10.5
3,539993,22379,RECYCLING BAG RETROSPOT,5,2011-01-04 10:00:00,2.10,13313,United Kingdom,10.5
4,539993,20718,RED RETROSPOT SHOPPER BAG,10,2011-01-04 10:00:00,1.25,13313,United Kingdom,12.5
5,539993,85099B,JUMBO BAG RED RETROSPOT,10,2011-01-04 10:00:00,1.95,13313,United Kingdom,19.5
6,539993,20682,RED RETROSPOT CHILDRENS UMBRELLA,6,2011-01-04 10:00:00,3.25,13313,United Kingdom,19.5
7,539993,22961,JAM MAKING SET PRINTED,12,2011-01-04 10:00:00,1.45,13313,United Kingdom,17.4
8,539993,22667,RECIPE BOX RETROSPOT,6,2011-01-04 10:00:00,2.95,13313,United Kingdom,17.7
9,539993,22898,CHILDRENS APRON APPLES DESIGN,8,2011-01-04 10:00:00,1.95,13313,United Kingdom,15.6

In [112]:
# tính M,
df_M = df_cs[['CustomerID','TotalPrice']].groupby("CustomerID").sum().rename(columns={'TotalPrice': 'Monetary'})

In [127]:
# tính F
df_F = df_cs[['CustomerID', 'InvoiceNo']].groupby('CustomerID').count().rename(columns={"InvoiceNo":"Frequency"})

In [128]:
snapshot_date = df_cs['InvoiceDate'].max()+ pd.Timedelta(days=1)

In [129]:
df_cs['days'] = (snapshot_date - df_cs['InvoiceDate']).dt.days
df_cs.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,TotalPrice,days
0,539993,22386,JUMBO BAG PINK POLKADOT,10,2011-01-04 10:00:00,1.95,13313,United Kingdom,19.5,178
1,539993,21499,BLUE POLKADOT WRAP,25,2011-01-04 10:00:00,0.42,13313,United Kingdom,10.5,178
2,539993,21498,RED RETROSPOT WRAP,25,2011-01-04 10:00:00,0.42,13313,United Kingdom,10.5,178
3,539993,22379,RECYCLING BAG RETROSPOT,5,2011-01-04 10:00:00,2.10,13313,United Kingdom,10.5,178
4,539993,20718,RED RETROSPOT SHOPPER BAG,10,2011-01-04 10:00:00,1.25,13313,United Kingdom,12.5,178

In [130]:
# tính R
df_R = df_cs[['CustomerID','days']].groupby('CustomerID').min().rename(columns={'days':'Recency'})

In [131]:
df_R.head()

            Recency
CustomerID
12346           164
12347            22
12348            87
12350           149
12352           101

In [132]:
df_F.head()

            Frequency
CustomerID
12346               1
12347              71
12348              11
12350              17
12352              38

In [134]:
pd.merge(df_R,df_F, left_index=True, right_index=True)

            Recency  Frequency
CustomerID
12346           164          1
12347            22         71
12348            87         11
12350           149         17
12352           101         38
...             ...        ...
18273            96          1
18280           116         10
18281            19          7
18283             8        322
18287            40         29

[2724 rows x 2 columns]

In [135]:
rfm = df_R.join([df_F,df_M])
rfm.head()

            Recency  Frequency  Monetary
CustomerID
12346           164          1  77183.60
12347            22         71   1494.16
12348            87         11    594.44
12350           149         17    334.40
12352           101         38   1561.81

In [136]:

# Calculate R_score: lower recency is better, so reverse labels
rfm['R_score'] = pd.qcut(rfm['Recency'], 5, labels=[5, 4, 3, 2, 1])

# Calculate F_score: higher frequency is better
rfm['F_score'] = pd.qcut(rfm['Frequency'], 5, labels=[1, 2, 3, 4, 5])

# Calculate M_score: higher monetary is better
rfm['M_score'] = pd.qcut(rfm['Monetary'], 5, labels=[1, 2, 3, 4, 5])

rfm.head()

            Recency  Frequency  Monetary R_score F_score M_score
CustomerID
12346           164          1  77183.60       1       1       5
12347            22         71   1494.16       4       4       5
12348            87         11    594.44       2       1       3
12350           149         17    334.40       1       2       2
12352           101         38   1561.81       2       3       5

In [137]:
rfm.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2724 entries, 12346 to 18287
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Recency    2724 non-null   int64
 1   Frequency  2724 non-null   int64
 2   Monetary   2724 non-null   float64
 3   R_score    2724 non-null   category
 4   F_score    2724 non-null   category
 5   M_score    2724 non-null   category
dtypes: category(3), float64(1), int64(2)
memory usage: 93.7+ KB

In [138]:
# Calculate RFM_score as the sum of R_score, F_score, and M_score
rfm['RFM_score'] = rfm['R_score'].astype(int) + rfm['F_score'].astype(int) + rfm['M_score'].astype(int)

# Define segments based on RFM_score
def segment_customer(score):
    if score >= 12:
        return 'High Value'
    elif score >= 9:
        return 'Medium Value'
    elif score >= 6:
        return 'Low Value'
    else:
        return 'Lost'

rfm['Segment'] = rfm['RFM_score'].apply(segment_customer)

rfm.head()

,Recency,Frequency,Monetary,R_score,F_score,M_score,RFM_score,Segment
CustomerID,,,,,,,,
12346,164,1,77183.60,1,1,5,7,Low Value
12347,22,71,1494.16,4,4,5,13,High Value
12348,87,11,594.44,2,1,3,6,Low Value
12350,149,17,334.40,1,2,2,5,Lost
12352,101,38,1561.81,2,3,5,10,Medium Value

In [139]:
rfm.to_csv('rfm.csv')