## Lecture 7: Pandas

In [1]:
#!pip install pandas

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
s1 = pd.Series([12,123,123,123])
print(s1)

0     12
1    123
2    123
3    123
dtype: int64

In [ ]:
s2 = pd.Series(data=[83,2,34,2], index=['a','b','c','d'])
print(s2)

a    83
b     2
c    34
d     2
dtype: int64

In [ ]:
arr = np.array([[1,2,3],
                [4,5,6]])
df1 = pd.DataFrame(data=arr, 
                   index=['r1','r2'],
                   columns=['c1','c2','c3'])
print(df1)

    c1  c2  c3
r1   1   2   3
r2   4   5   6

In [ ]:
df2 = pd.DataFrame({'col1':{"c1":1,"c2":2,"c3":3},
                   'col2':{"c1":1,"c2":2,"c3":3}})
df2

    col1  col2
c1     1     1
c2     2     2
c3     3     3

In [ ]:
type(s1)

pandas.core.series.Series

In [ ]:
type(df1)

pandas.core.frame.DataFrame

In [ ]:
s1

0     12
1    123
2    123
3    123
dtype: int64

In [ ]:
s1.values #data

array([ 12, 123, 123, 123])

In [ ]:
s1.index #index

RangeIndex(start=0, stop=4, step=1)

In [ ]:
s2.index

Index(['a', 'b', 'c', 'd'], dtype='object')

In [ ]:
df1.values

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
df2.values

array([[1, 1],
       [2, 2],
       [3, 3]])

In [ ]:
df1

    c1  c2  c3
r1   1   2   3
r2   4   5   6

In [ ]:
df1.index

Index(['r1', 'r2'], dtype='object')

In [ ]:
df1.columns

Index(['c1', 'c2', 'c3'], dtype='object')

In [ ]:
s2

a    83
b     2
c    34
d     2
dtype: int64

In [ ]:
s2['c']

np.int64(34)

In [ ]:
s2['c'] = 'new'
s2

C:\Users\Admin\AppData\Local\Temp\ipykernel_10036\2078390357.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'new' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  s2['c'] = 'new'

a     83
b      2
c    new
d      2
dtype: object

In [ ]:
s1

0     12
1    123
2    123
3    123
dtype: int64

In [ ]:
s1[:2]

0     12
1    123
dtype: int64

In [ ]:
s2

a     83
b      2
c    new
d      2
dtype: object

In [ ]:
s2[:2]

a    83
b     2
dtype: object

In [ ]:
s2['a':'b']

a    83
b     2
dtype: object

In [ ]:
df1

    c1  c2  c3
r1   1   2   3
r2   4   5   6

In [ ]:
df1['c1']

r1    1
r2    4
Name: c1, dtype: int64

In [ ]:
df1[['c1','c2']]

    c1  c2
r1   1   2
r2   4   5

In [ ]:
df1

    c1  c2  c3
r1   1   2   3
r2   4   5   6

In [ ]:
df1.loc['r1']

c1    1
c2    2
c3    3
Name: r1, dtype: int64

In [ ]:
df1.iloc[1]

c1    4
c2    5
c3    6
Name: r2, dtype: int64

In [ ]:
df2

    col1  col2
c1     1     1
c2     2     2
c3     3     3

In [ ]:
df2.iloc[1:]

    col1  col2
c2     2     2
c3     3     3

In [ ]:
df = pd.DataFrame({
    'A': [1, 2, 3],
    'B': [4, 5, 6],
    'C': [7, 8, 9]})
df

   A  B  C
0  1  4  7
1  2  5  8
2  3  6  9

In [ ]:
#add column
df['new_col'] = [1,1,1]
df

   A  B  C  new_col
0  1  4  7        1
1  2  5  8        1
2  3  6  9        1

In [ ]:
df.loc['new_id'] = [4,4,4,4]
df

        A  B  C  new_col
0       1  4  7        1
1       2  5  8        1
2       3  6  9        1
new_id  4  4  4        4

In [ ]:
df.drop(columns=['new_col'], inplace=True)

In [ ]:
df

        A  B  C
0       1  4  7
1       2  5  8
2       3  6  9
new_id  4  4  4

In [ ]:
df.drop(index='new_id', inplace= True)

In [ ]:
df

   A  B  C
0  1  4  7
1  2  5  8
2  3  6  9

In [ ]:
#filter: df[filter_condition]
df[df['A']%2==1]

   A  B  C
0  1  4  7
2  3  6  9

In [ ]:
df[df['B']>=5]

   A  B  C
1  2  5  8
2  3  6  9

In [ ]:
df_retail = pd.read_csv('Data\OnlineRetail.csv')
type(df_retail)

pandas.core.frame.DataFrame

In [ ]:
df_retail.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,539993,22386,JUMBO BAG PINK POLKADOT,10,2011-01-04 10:00:00,1.95,13313.0,United Kingdom
1,539993,21499,BLUE POLKADOT WRAP,25,2011-01-04 10:00:00,0.42,13313.0,United Kingdom
2,539993,21498,RED RETROSPOT WRAP,25,2011-01-04 10:00:00,0.42,13313.0,United Kingdom
3,539993,22379,RECYCLING BAG RETROSPOT,5,2011-01-04 10:00:00,2.10,13313.0,United Kingdom
4,539993,20718,RED RETROSPOT SHOPPER BAG,10,2011-01-04 10:00:00,1.25,13313.0,United Kingdom

In [ ]:
df_retail.tail()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
203417,558637,22032,BOTANICAL LILY GREETING CARD,12,2011-06-30 20:08:00,0.42,17891.0,United Kingdom
203418,558637,22028,PENNY FARTHING BIRTHDAY CARD,12,2011-06-30 20:08:00,0.42,17891.0,United Kingdom
203419,558637,22033,BOTANICAL ROSE GREETING CARD,12,2011-06-30 20:08:00,0.42,17891.0,United Kingdom
203420,558637,22029,SPACEBOY BIRTHDAY CARD,12,2011-06-30 20:08:00,0.42,17891.0,United Kingdom
203421,558637,22024,RAINY LADIES BIRTHDAY CARD,12,2011-06-30 20:08:00,0.42,17891.0,United Kingdom

In [ ]:
df_retail.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 203422 entries, 0 to 203421
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    203422 non-null  object
 1   StockCode    203422 non-null  object
 2   Description  202623 non-null  object
 3   Quantity     203422 non-null  int64
 4   InvoiceDate  203422 non-null  object
 5   UnitPrice    203422 non-null  float64
 6   CustomerID   150039 non-null  float64
 7   Country      203422 non-null  object
dtypes: float64(2), int64(1), object(5)
memory usage: 12.4+ MB

In [ ]:
df

   A  B  C
0  1  4  7
1  2  5  8
2  3  6  9

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       3 non-null      int64
 1   B       3 non-null      int64
 2   C       3 non-null      int64
dtypes: int64(3)
memory usage: 204.0+ bytes

In [ ]:
df_retail.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 203422 entries, 0 to 203421
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    203422 non-null  object
 1   StockCode    203422 non-null  object
 2   Description  202623 non-null  object
 3   Quantity     203422 non-null  int64
 4   InvoiceDate  203422 non-null  object
 5   UnitPrice    203422 non-null  float64
 6   CustomerID   150039 non-null  float64
 7   Country      203422 non-null  object
dtypes: float64(2), int64(1), object(5)
memory usage: 12.4+ MB

In [ ]:
len(set(df_retail['StockCode']))

3531

In [ ]:
df_retail['StockCode'].value_counts()

StockCode
22423     1080
85123A    1079
47566      965
85099B     924
20725      741
          ...
23039        1
23272        1
23113        1
84551        1
84679        1
Name: count, Length: 3531, dtype: int64

In [ ]:
df_retail['InvoiceNo'].value_counts()

InvoiceNo
558475     705
540551     502
540848     460
541421     455
541827     429
          ...
548104       1
539996       1
558624       1
C558615      1
558529       1
Name: count, Length: 10770, dtype: int64

In [ ]:
df_retail.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,539993,22386,JUMBO BAG PINK POLKADOT,10,2011-01-04 10:00:00,1.95,13313.0,United Kingdom
1,539993,21499,BLUE POLKADOT WRAP,25,2011-01-04 10:00:00,0.42,13313.0,United Kingdom
2,539993,21498,RED RETROSPOT WRAP,25,2011-01-04 10:00:00,0.42,13313.0,United Kingdom
3,539993,22379,RECYCLING BAG RETROSPOT,5,2011-01-04 10:00:00,2.10,13313.0,United Kingdom
4,539993,20718,RED RETROSPOT SHOPPER BAG,10,2011-01-04 10:00:00,1.25,13313.0,United Kingdom

In [ ]:
df_retail['TotalPrice'] = df_retail['Quantity']*df_retail['UnitPrice']
df_retail.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,TotalPrice
0,539993,22386,JUMBO BAG PINK POLKADOT,10,2011-01-04 10:00:00,1.95,13313.0,United Kingdom,19.5
1,539993,21499,BLUE POLKADOT WRAP,25,2011-01-04 10:00:00,0.42,13313.0,United Kingdom,10.5
2,539993,21498,RED RETROSPOT WRAP,25,2011-01-04 10:00:00,0.42,13313.0,United Kingdom,10.5
3,539993,22379,RECYCLING BAG RETROSPOT,5,2011-01-04 10:00:00,2.10,13313.0,United Kingdom,10.5
4,539993,20718,RED RETROSPOT SHOPPER BAG,10,2011-01-04 10:00:00,1.25,13313.0,United Kingdom,12.5

In [ ]:
%timeit sum(df_retail['TotalPrice'])
%timeit df_retail['TotalPrice'].sum()

15.3 ms ± 232 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)
162 μs ± 3.04 μs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)

In [ ]:
df_retail['TotalPrice'].sum()

np.float64(3648993.741)

In [ ]:
df_retail.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 203422 entries, 0 to 203421
Data columns (total 9 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    203422 non-null  object
 1   StockCode    203422 non-null  object
 2   Description  202623 non-null  object
 3   Quantity     203422 non-null  int64
 4   InvoiceDate  203422 non-null  object
 5   UnitPrice    203422 non-null  float64
 6   CustomerID   150039 non-null  float64
 7   Country      203422 non-null  object
 8   TotalPrice   203422 non-null  float64
dtypes: float64(3), int64(1), object(5)
memory usage: 14.0+ MB

In [ ]:
df_retail.isnull().sum()

InvoiceNo          0
StockCode          0
Description      799
Quantity           0
InvoiceDate        0
UnitPrice          0
CustomerID     53383
Country            0
TotalPrice         0
dtype: int64

In [ ]:
df_cs = df_retail.dropna(subset=['CustomerID'])
df_cs

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,TotalPrice
0,539993,22386,JUMBO BAG PINK POLKADOT,10,2011-01-04 10:00:00,1.95,13313.0,United Kingdom,19.50
1,539993,21499,BLUE POLKADOT WRAP,25,2011-01-04 10:00:00,0.42,13313.0,United Kingdom,10.50
2,539993,21498,RED RETROSPOT WRAP,25,2011-01-04 10:00:00,0.42,13313.0,United Kingdom,10.50
3,539993,22379,RECYCLING BAG RETROSPOT,5,2011-01-04 10:00:00,2.10,13313.0,United Kingdom,10.50
4,539993,20718,RED RETROSPOT SHOPPER BAG,10,2011-01-04 10:00:00,1.25,13313.0,United Kingdom,12.50
...,...,...,...,...,...,...,...,...,...
203417,558637,22032,BOTANICAL LILY GREETING CARD,12,2011-06-30 20:08:00,0.42,17891.0,United Kingdom,5.04
203418,558637,22028,PENNY FARTHING BIRTHDAY CARD,12,2011-06-30 20:08:00,0.42,17891.0,United Kingdom,5.04
203419,558637,22033,BOTANICAL ROSE GREETING CARD,12,2011-06-30 20:08:00,0.42,17891.0,United Kingdom,5.04
203420,558637,22029,SPACEBOY BIRTHDAY CARD,12,2011-06-30 20:08:00,0.42,17891.0,United Kingdom,5.04
203421,558637,22024,RAINY LADIES BIRTHDAY CARD,12,2011-06-30 20:08:00,0.42,17891.0,United Kingdom,5.04

In [ ]:
df_cs.isnull().sum()

InvoiceNo      0
StockCode      0
Description    0
Quantity       0
InvoiceDate    0
UnitPrice      0
CustomerID     0
Country        0
TotalPrice     0
dtype: int64

In [ ]:
df_cs.info()

<class 'pandas.core.frame.DataFrame'>
Index: 150039 entries, 0 to 203421
Data columns (total 9 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    150039 non-null  object
 1   StockCode    150039 non-null  object
 2   Description  150039 non-null  object
 3   Quantity     150039 non-null  int64
 4   InvoiceDate  150039 non-null  object
 5   UnitPrice    150039 non-null  float64
 6   CustomerID   150039 non-null  float64
 7   Country      150039 non-null  object
 8   TotalPrice   150039 non-null  float64
dtypes: float64(3), int64(1), object(5)
memory usage: 11.4+ MB

In [ ]:
df_retail['CustomerID'] = df_cs['CustomerID'].astype('int').astype('str')

In [ ]:
df_cs['InvoiceDate'] = pd.to_datetime(df_cs['InvoiceDate'])

C:\Users\Admin\AppData\Local\Temp\ipykernel_10036\2776208959.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_cs['InvoiceDate'] = pd.to_datetime(df_cs['InvoiceDate'])

In [ ]:
df_cs[df_cs['InvoiceDate'].dt.quarter == 1]

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,TotalPrice
0,539993,22386,JUMBO BAG PINK POLKADOT,10,2011-01-04 10:00:00,1.95,13313.0,United Kingdom,19.50
1,539993,21499,BLUE POLKADOT WRAP,25,2011-01-04 10:00:00,0.42,13313.0,United Kingdom,10.50
2,539993,21498,RED RETROSPOT WRAP,25,2011-01-04 10:00:00,0.42,13313.0,United Kingdom,10.50
3,539993,22379,RECYCLING BAG RETROSPOT,5,2011-01-04 10:00:00,2.10,13313.0,United Kingdom,10.50
4,539993,20718,RED RETROSPOT SHOPPER BAG,10,2011-01-04 10:00:00,1.25,13313.0,United Kingdom,12.50
...,...,...,...,...,...,...,...,...,...
99597,548548,22423,REGENCY CAKESTAND 3 TIER,1,2011-03-31 19:54:00,12.75,17781.0,United Kingdom,12.75
99598,548548,21361,LOVE LARGE WOOD LETTERS,7,2011-03-31 19:54:00,12.75,17781.0,United Kingdom,89.25
99599,548549,84763,ZINC FINISH 15CM PLANTER POTS,100,2011-03-31 19:55:00,1.06,16365.0,United Kingdom,106.00
99600,548549,22222,CAKE PLATE LOVEBIRD WHITE,1,2011-03-31 19:55:00,4.95,16365.0,United Kingdom,4.95
99601,548549,22776,SWEETHEART CAKESTAND 3 TIER,1,2011-03-31 19:55:00,9.95,16365.0,United Kingdom,9.95

In [ ]:
df_cs.describe()

,Quantity,InvoiceDate,UnitPrice,CustomerID,TotalPrice
count,150039.000000,150039,150039.000000,150039.000000,150039.000000
mean,12.527296,2011-04-06 06:42:14.911323392,3.884802,15240.234832,21.153815
min,-74215.000000,2011-01-04 10:00:00,0.000000,12346.000000,-77183.600000
25%,2.000000,2011-02-22 17:13:00,1.250000,13791.000000,4.990000
50%,6.000000,2011-04-07 09:28:00,1.950000,15061.000000,12.600000
75%,12.000000,2011-05-19 16:31:00,3.750000,16771.000000,19.800000
max,74215.000000,2011-06-30 20:08:00,38970.000000,18287.000000,77183.600000
std,275.131638,NaN,108.443379,1717.658493,327.477275